# Generated by Django 2.2 on 2022-05-03 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0002_auto_20220503_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='content',
            field=models.TextField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='username',
            field=models.CharField(max_length=30, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='news',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
