# Generated by Django 2.2 on 2022-05-04 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0004_auto_20220503_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='active',
            field=models.CharField(default='a', max_length=1),
        ),
    ]
