# Generated by Django 2.2 on 2022-05-04 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0007_auto_20220504_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='delete_status',
            field=models.BooleanField(choices=[(True, 'Удалено администратором'), (False, '')], default=False),
        ),
    ]
