# Generated by Django 2.2 on 2022-05-04 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0008_comments_delete_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='delete_status',
            field=models.BooleanField(choices=[(True, 'Удалено администратором'), (False, '')], default=False, verbose_name='Статус'),
        ),
    ]
