# Generated by Django 2.2 on 2022-05-12 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0010_comments_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-created_at'], 'permissions': (('can_activate', 'Can activate news'),)},
        ),
    ]
