# Generated by Django 2.2 on 2022-05-12 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0012_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='newspaper.Tags'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='title',
            field=models.CharField(default='Другое', max_length=20, verbose_name='Тег'),
        ),
    ]
