# Generated by Django 2.2 on 2022-05-12 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0013_auto_20220512_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='tag',
            field=models.ForeignKey(default='Другое', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='newspaper.Tags'),
        ),
    ]
