# Generated by Django 2.2 on 2022-05-12 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0015_auto_20220512_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='active',
            field=models.BooleanField(choices=[(True, 'Active'), (False, 'Deactive')], default=False),
        ),
    ]
