# Generated by Django 2.2 on 2022-05-11 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11, verbose_name='Номер телефона')),
                ('is_verify', models.BooleanField(default=False, verbose_name='Верификация')),
                ('num_of_news', models.IntegerField(default=0, verbose_name='Чисто опубликованных новостей')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='who', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'db_table': 'Информация о пользователе',
            },
        ),
    ]
