# Generated by Django 2.2 on 2022-05-11 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0004_auto_20220511_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_verify',
            field=models.BooleanField(choices=[(True, 'Верифицирован'), (False, 'Не верифицирован')], default=False, verbose_name='Верификация'),
        ),
    ]
