# Generated by Django 2.2 on 2022-05-12 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0005_auto_20220511_2022'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': (('can_verify', 'Can Verify Users'),)},
        ),
    ]
