# Generated by Django 2.2 on 2022-05-12 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0007_auto_20220512_1314'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': (('can_verify', 'Can Verify Users'),)},
        ),
    ]
