# Generated by Django 2.2 on 2022-05-03 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0003_auto_20220503_1739'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-created_at']},
        ),
    ]
